[phases.setup]
nixPkgs = ["python3", "cairo", "pango", "libjpeg", "giflib", "librsvg", "pixman", "pkg-config", "gcc", "gnumake"]
nixLibs = ["cairo", "pango", "libjpeg", "giflib", "librsvg"]

[phases.install]
cmds = ["npm config set python /nix/var/nix/profiles/default/bin/python3", "npm ci --only=production"]

[start]
cmd = "npm start"
